name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Update every hour
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Kolkata
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
